### ISSUE TITLE
Talsec Memory Leak Found by Instruments

### ISSUE THREAD

**Issue by Shafran123** [talsec/Free-RASP-iOS#13]
Introduction

I have been using Talsec free version in one of my iOS application.sometimes app took time to load.when I ran a instrument check I found that the memory has been leaking form talsec lib core

I am staring talsec in View Controller

![Screenshot 2024-01-10 at 4 01 19 PM](https://github.com/talsec/Free-RASP-iOS/assets/12469262/c6258b47-443e-4d01-967f-ac7f85c440cf)

Is there any fix for this

**Comment by msikyna** [comment]
Hello @Shafran123 ,
thank you for reporting this, we will look at it soon.

Kind regards,
Talsec team

**Comment by msikyna** [comment]
Hello @Shafran123 ,
we have found the memory leak. The issue is fixed and will be a part of next release. Thank you for reporting it!

Kind regards,
Talsec team

**Comment by msikyna** [comment]
Hello @Shafran123 , 
the new version [6.1.2](https://github.com/talsec/Free-RASP-iOS/releases/tag/6.1.2) fixing the issue has been published.

Kind regards,
Talsec team
