### ISSUE TITLE
Option for downloading a framework

### ISSUE THREAD

**Issue by aldrnikolajev** [talsec/Free-RASP-iOS#2]
Hello

Looking forward to integrate free version of Talsec in our app! However there are some obstacles.
There is no direct download link for the framework which will force us to paste it to our codebase and additionally push to the repository.
 
Is it possible to have a direct download link for free version of Talsec? It could be included in the `Releases` page perhaps 🤔

**Comment by talsec-app** [comment]
Hello @aldrnikolajev ,
we will look into that. By download link you mean https://downgit.github.io/#/home?
Kind regards,
Talsec team

**Comment by aldrnikolajev** [comment]
> Hello @aldrnikolajev ,
> we will look into that. By download link you mean https://downgit.github.io/#/home?
> Kind regards,
> Talsec team

Thanks for the rapid response!

No, didn't mean downgit. Even downgit doesn't work for folder like structure 🙂.
What I meant is to include a zipped versions of frameworks under Releases page (attached an image).
That will allow us to download the zipped version of framework via `Carthage` (a dependency manager for iOS) and then we will link the library in the app.  

![image](https://user-images.githubusercontent.com/48324245/198036558-fd672bca-7e01-4257-a49a-53a3e3e0a146.png)

**Comment by talsec-app** [comment]
Hello @aldrnikolajev ,
we have added zipped versions under last version on the Release page #v3.2.0. Would that work for you? If so, we will continue doing this in the future versions and add this to the documentation as well.

Kind regards,
Talsec team

**Comment by aldrnikolajev** [comment]
Hey @talsec-app! 

Thanks, that worked really well!
