### ISSUE TITLE
The signature of "TalsecRuntime.xcframework" cannot be verified

### ISSUE THREAD

**Issue by schmittsfn** [talsec/Free-RASP-iOS#25]
I'm getting the following error:

```
The signature of "TalsecRuntime.xcframework" cannot be verified.
The signing certificate has been revoked
(CSSMERR_TP_CERT_REVOKED)
```

I am behind a VPN. Could this be the issue? Or does the framework's certificate need to be updated?

**Comment by msikyna** [comment]
Hi @schmittsfn ,
thank you for reporting the issue, we will look at it.

Kind regards,
Talsec team

**Comment by schmittsfn** [comment]
Thank you @msikyna. Do you have an update?

**Comment by msikyna** [comment]
Hello @schmittsfn ,
the new version has been just released also with the dSYMs: https://github.com/talsec/Free-RASP-iOS/releases/tag/6.6.1

Could you try? Thank you!
